name: Fetch LHC data

on:
  schedule:
    - cron: "*/10 * * * *"    # every 10 minutes
  workflow_dispatch:          # manual trigger

permissions:
  contents: write             # allow pushing changes

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch latest & append history (trim to 50 days / 7200 pts)
        run: node fetch-lhc.mjs

      - name: Commit and push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add data/latest.json data/lhc_history.jsonl
            git commit -m "data: update latest + append history (10min)"
            git push
          else
            echo "No changes."
          fi

