name: LHC history fetch
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch
        run: |
          mkdir -p data
          URL="https://lhcstatus2.ovh/vistars.json"
          TS=$(date +%s)
          JSON=$(curl -fsSL "$URL" || echo '{}')
          # Werte grob extrahieren (robust/simple)
          ENERGY=$(echo "$JSON" | grep -Eo '"energy"[^0-9]*[0-9.]+' | grep -Eo '[0-9.]+' | head -n1)
          IB1=$(echo "$JSON" | grep -Ei 'ib1|beam.?1' | grep -Eo '[0-9]+' | head -n1)
          IB2=$(echo "$JSON" | grep -Ei 'ib2|beam.?2' | grep -Eo '[0-9]+' | head -n1)
          echo "{\"t\":$TS,\"energy\":${ENERGY:-null},\"ib1\":${IB1:-null},\"ib2\":${IB2:-null}}" >> data/lhc_history.jsonl
          # nur letzte 6h behalten
          tail -n 720 data/lhc_history.jsonl > data/.tmp && mv data/.tmp data/lhc_history.jsonl
      - name: Commit
        run: |
          git config user.name  "gh-actions"
          git config user.email "actions@github.com"
          git add data/lhc_history.jsonl
          git commit -m "update history" || echo "no changes"
          git push

