name: LHC History (last 1h)

on:
  schedule:
    - cron: "*/1 * * * *"  # jede Minute
  workflow_dispatch: {}     # manuell startbar

permissions:
  contents: write  # erlaubt commit/push mit GITHUB_TOKEN

concurrency:
  group: lhc-history
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          mkdir -p scripts data
          npm init -y >/dev/null 2>&1 || true
          npm i --no-audit --no-fund --silent

      - name: Update history file
        run: node scripts/update_history.mjs

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(history): append sample & trim to last hour"
            git push
          fi
