name: Pull Vistars JSON

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten (GitHub-Minimum)
  workflow_dispatch:        # manuell startbar im Actions-Tab

permissions:
  contents: write           # erlaubt commit/push

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch + update data
        env:
          SRC_URL: https://lhcstatus2.ovh/vistars.json
        run: node scripts/pull.mjs

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain data/) ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/latest.json data/lhc_history.jsonl
            git commit -m "data: update from Vistars [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
